name: Daily Digest
on:
  schedule:
    - cron: "30 22 * * *"   # 07:30 KST daily (UTC 22:30)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Sync env (frozen)
        run: uv sync --frozen
      - name: Build digest and email
        env:
          ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
          FRED_API_KEY:     ${{ secrets.FRED_API_KEY }}
          SMTP_USER:        ${{ secrets.SMTP_USER }}
          SMTP_PASS:        ${{ secrets.SMTP_PASS }}
          DIGEST_TO:        ${{ secrets.DIGEST_TO }}
        run: |
          python -m assistant.composer.run_digest > digest.md
          python - <<PY
from assistant.senders.smtp_sender import send_email
import os
html = open("digest.md","r").read().replace("\n","<br/>")
send_email(to=os.environ["DIGEST_TO"], subject="Daily Quant Digest", html_or_md=html)
PY
