name: Daily Digest

on:
  schedule:
    - cron: "30 22 * * *" # 07:30 KST
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Sync environment
        run: uv sync --frozen

      - name: Run Daily Digest Agent
        env:
          OLLAMA_ENDPOINT: ${{ secrets.OLLAMA_ENDPOINT }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          DIGEST_TO: ${{ secrets.DIGEST_TO }}
          DRY_RUN: ${{ secrets.DRY_RUN }}
        run: uv run python -m assistant.composer.run_digest

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: digest.md